services:
  gui_container:
    build:
      context: ./GUI
    network_mode: host
    privileged: true
    container_name: gui_container
    volumes:
      - ./GUI:/app
      - /dev:/dev
    environment:
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-1}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - PYTHONUNBUFFERED=1
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && python3 ws_ros2_bridge.py & python3 web_camera_server.py & node server.js"

  supervisor_container:
    build:
      context: ./ROAR-Supervisor
    network_mode: host
    privileged: true
    container_name: supervisor_container
    volumes:
      - /dev:/dev
    environment:
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-1}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - PYTHONUNBUFFERED=1
    command: ros2 launch supervisor multi_launch.py