services:

  gui_container:
    build:
      context: ./navStack_2026/GUI
    network_mode: host
    container_name: gui_container
    environment:
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - PYTHONUNBUFFERED=1
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml:ro
    # npm start goes in the background, python bridge stays in the foreground to keep the container alive
    command: bash -c "npm start & python3 ws_ros2_bridge.py"
  supervisor_container:
    build:
      context: ./ROAR-Supervisor
    network_mode: host
    container_name: supervisor_container
    environment:
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - PYTHONUNBUFFERED=1
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml:ro
    command: ros2 launch supervisor multi_launch.py