services:
  gui_container:
    build:
      context: ./GUI
    network_mode: host
    container_name: gui_container
    volumes:
      - ./GUI:/app
      - /app/node_modules
    environment:
      - PYTHONUNBUFFERED=1
      - ROVER_IP=${ROVER_IP:-192.168.0.100}
    command: node server.js
