nodes:
  node1: "ros2 run supervisor my_first_node"
  node2: "ros2 run supervisor my_second_node"
  node3: "ros2 run supervisor my_third_node"
  camera_driver: "ros2 run usb_cam usb_cam_node_exe" # Example

missions:
  drilling: [node1, node2]
  navigation: [node2, node3]
  sampling: [node1, node3]
  maintenance: [node1, node2, node3]
  teleoperation: [node2]